# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b23b975de16550becbbc229963a96b247e29cdc58efd6c339e6178db7dba6f943fcf8d378a3bdb265dd2de0212eca700069f5715727cd6171799f84e1bb8203
  app_host: localhost:3000
  jwt_secret_key: ec997d184db4ffa90eed5019fccbad709a0e5396e1a48ae9692e45c21b55346415a87c2f8d91203745c7e025420880f488a9dda818600047f32032d0be4d9f72
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  access_token: <%= ENV["ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>

test:
  secret_key_base: 6c269436a12888d0602749e34cd70f526c38c71ddd7dfe5a559630923839099aeac19e8a22ae35f85123c0de6e8e4e502ef4d5f4deb5d852e63b19bbd792cf55
  app_host: test.host
  jwt_secret_key: fd5e64049ab1a8e92067ab0a9ebbb847188dc3f425cda8f1aba109f93510080f1b187509cde152a88e5ecc964a895bb895df7a7d04299a0b3d836112aab292bb
  twilio_phone_number: '+015151515151'
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  access_token: <%= ENV["ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_host: <%= ENV["APP_HOST"] %>
  jwt_secret_key: <%= ENV["JWT_SECRET_KEY"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
